Repository Tboy-AK/Basic-Cloud-File-Storage-System, pull requests merged in 2020-07, with the labels that each got.

#8 ch(project-setup):[Finishes #1]
  README.md
  package-lock.json
  package.json
Labels: chore

#10 ft(read-file):[Finishes #5]
  readDelete.js
Labels: enhancement

#11 ft(crud-commands):[Finishes #3]
  index.js
  package.json
  server.js
Labels: enhancement

#13 ch(read-file):runs unit tests[Finishes #5]
  readDelete.js
  spec/readFileSpec.js
  spec/support/jasmine.json
  spec/support/resources/1.txt
Labels: chore, enhancement

#12 Ft delete file #6
  package.json
  readDelete.js
  spec/deleteFileSpec.js
Labels: enhancement

#14 ft(user-reg):[Finishes #2]
  userReg.js
Labels: enhancement

#21 ch(codebase-structure):[Finishes #16]
  controllers/deleteFile.js
  controllers/readFile.js
  database/drives/tboyak/1.txt
  database/users.json
  package.json
  server.js
  spec/deleteFileSpec.js
  spec/readFileSpec.js
Labels: chore

#26 ft(webservice):[Finishes #25]
  controllers/deleteFile.js
  controllers/filesController.js
  controllers/readFile.js
  controllers/statsController.js
  controllers/usersController.js
  database/stats/server-stats.json
  index.js
  package.json
  server.js
  spec/deleteFileSpec.js
  spec/readFileSpec.js
  userReg.js
Labels: enhancement

#27 ft(analytics):[Finishes #20]
  analytics/getAllFiles.js
Labels: enhancement

#22 ft(search-phrase):[Finishes #18]
  searchPhrase.js
Labels: enhancement

#29 ft(create-file):with instructive root directory[Finishes #28 #19 #4]
  .eslintrc.json
  analytics/getAllFiles.js
  controllers/filesController.js
  controllers/navControllers.js
  controllers/statsController.js
  controllers/usersController.js
  database/stats/server-stats.json
  package-lock.json
  package.json
  server.js
Labels: enhancement

#30 bg(create-file)
  controllers/filesController.js
  database/stats/server-stats.json
  database/users.json
Labels: bug

#32 bg(node-main):node server.js
  package.json
Labels: bug
